Traceback (most recent call last):
  File "ExceptionClass.py", line 461, in <module>
    5 / 0
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "ExceptionClass.py", line 461, in <module>
    5 / 0
ZeroDivisionError: division by zero
